package com.spring.h2;

import com.spring.h2.dto.TodoRequest;
import com.spring.h2.dto.TodoResponse;
import com.spring.h2.service.TodoService;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.ResponseEntity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class TodoSteps {

    @Autowired
    private TestRestTemplate testRestTemplate;

    @Autowired
    private TodoService todoService;

    private List<TodoRequest> todoRequests = new ArrayList<>();
    private List<ResponseEntity<TodoResponse>> postResponses = new ArrayList<>();
    private ResponseEntity<TodoResponse[]> getResponse;

    @Given("the following todo details:")
    public void theFollowingTodoDetails(List<Map<String, String>> todoDetails) {
        todoRequests.clear();
        for (Map<String, String> details : todoDetails) {
            TodoRequest todoRequest = new TodoRequest(details.get("todo"), Boolean.parseBoolean(details.get("completed")));
            todoRequests.add(todoRequest);
        }
    }

    @When("I send a POST request to {string} with this todo")
    public void iSendAPOSTRequestToWithThisTodo(String endpoint) {
        postResponses.clear();
        for (TodoRequest todoRequest : todoRequests) {
            HttpEntity<TodoRequest> requestEntity = new HttpEntity<>(todoRequest);
            ResponseEntity<TodoResponse> response = testRestTemplate.postForEntity(endpoint, requestEntity, TodoResponse.class);
            postResponses.add(response);
        }
    }

    @Then("the response should contain the saved todo with an auto-generated ID")
    public void theResponseShouldContainTheSavedTodoWithAnAutoGeneratedID() {
        for (int i = 0; i < postResponses.size(); i++) {
            ResponseEntity<TodoResponse> response = postResponses.get(i);
            TodoRequest expected = todoRequests.get(i);
            TodoResponse actual = response.getBody();

            assertNotNull(actual, "Saved todo should not be null");
            assertNotNull(actual.getId(), "Saved todo ID should not be null");
            assertEquals(expected.getTodo(), actual.getTodo(), "Todo text should match");
            assertEquals(expected.isComplete(), actual.isComplete(), "Completion status should match");
        }
    }

    @And("the status code should be {int}")
    public void theStatusCodeShouldBe(int statusCode) {
        for (ResponseEntity<?> response : postResponses) {
            assertEquals(statusCode, response.getStatusCode().value(), "Status code should match");
        }
    }

    @And("the saved todo should exists in the database")
    public void theSavedTodoShouldExistsInTheDatabase() {
        for (ResponseEntity<TodoResponse> response : postResponses) {
            TodoResponse savedTodo = response.getBody();
            assertNotNull(savedTodo, "Saved todo should not be null");
            TodoResponse retrievedTodo = todoService.getTodoById(savedTodo.getId());
            assertEquals(savedTodo, retrievedTodo, "Saved todo should match the retrieved todo from the database");
        }
    }

    @When("I send a GET request to {string}")
    public void iSendAGETRequestTo(String endpoint) {
        getResponse = testRestTemplate.getForEntity(endpoint, TodoResponse[].class);
    }

    @Then("the response should contain the following todos:")
    public void theResponseShouldContainTheFollowingTodos(List<Map<String, String>> expectedTodos) {
        TodoResponse[] todos = getResponse.getBody();
        assertNotNull(todos, "Todos response should not be null");

        for (int i = 0; i < expectedTodos.size(); i++) {
            Map<String, String> expectedTodo = expectedTodos.get(i);
            assertEquals(expectedTodo.get("todo"), todos[i].getTodo(), "Todo text should match");
            assertEquals(Boolean.parseBoolean(expectedTodo.get("completed")), todos[i].isComplete(), "Completion status should match");
        }
    }

    @And("the response header {string} should be {string}")
    public void theResponseHeaderShouldBe(String headerName, String expectedHeaderValue) {
        assertEquals(expectedHeaderValue, getResponse.getHeaders().getFirst(headerName), "Response header value should match");
    }

    @And("the size of list should be {int}")
    public void theSizeOfListShouldBe(int expectedSize) {
        assertNotNull(getResponse.getBody(), "Todos response should not be null");
        assertEquals(expectedSize, getResponse.getBody().length, "Size of todos list should match");
    }
}
