spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbox
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

flyway:
  enabled: true
  url: jdbc:mysql://localhost:3306/springbox
  user: root
  password: root
  schemas:
    - public
  locations:
    - classpath:db/migration
  baseline-on-migrate: true