name: Build and Test

on:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-test:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      # Grant execution permissions for the Makefile
      - name: Makefile Permissions
        run: chmod +x Makefile

      # Install Gradle Wrapper if needed
      - name: Ensure Gradle Wrapper
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper
          fi

      # Run Makefile's pipeline target
      - name: Run Pipeline
        run: make pipeline
